# Generated by Django 5.2.3 on 2025-06-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_order_end_time_alter_order_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
