# Generated by Django 5.2.3 on 2025-06-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_end_date_order_start_date_alter_order_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
    ]
