# Generated by Django 5.2.3 on 2025-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_order_end_date_remove_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
